name: PR labelling
on:
  pull_request:

jobs:
  label:
    name: Label db migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
